name: deploy-sa
on:
  workflow_dispatch:
  
env:
  RG_NAME: RG5
  RG_LOC: WestEurope
 
 
permissions:
  id-token: write
  contents: read
 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: sign in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{secrets.AZ_CLIENT_ID}}
          tenant-id: ${{secrets.AZ_TENANT_ID}}
          subscription-id: ${{secrets.AZ_SUB_ID}}

      - name: deploy RG
        uses: azure/cli@v1
        with:
         inlineScript:
          az group create --name ${{env.RG_NAME}}  --location ${{env.RG_LOC}}
          
      - name: deploy storage
        uses: azure/arm-deploy@v1
        with:
         deploymentName: ${{github.run_Number}}
         resourceGroupName: ${{env.RG_NAME}}
         template: ./storage.bicep
